### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by florianpeninon** [aaronagray/meteor-susy#3]
Hi,
I'm trying to use this package but it doesn't seem to work.
I followed the readme and in my **style.scss** I wrote :

``` SCSS
@import ".meteor/local/build/programs/server/assets/packages/meta_susy/susy";

body { @include container(80em); }
.sticky-nav { @include span(25%); }
```

But it doesn't apply, did I do something wrong?

**Comment by samusgray** [comment]
Thanks for reporting this. Will you please share the output from running `meteor list`? I'd like to see what packages and version of Susy you have installed in this project.

**Comment by florianpeninon** [comment]
Here is the result of the command :

```
$ meteor list
autopublish      1.0.2  Publish the entire database to all clients
insecure         1.0.2  Allow all database writes by default
meta:susy        2.1.1  Powerful grids for the web.
meteor-platform  1.2.1  Include a standard set of Meteor packages in your app
```

**Comment by samusgray** [comment]
It looks like the `fourseven:scss` dependency wasn't added when you installed Susy. It should have done this by default, so I'll look into it for future install. For now, will you please try `meteor add fourseven:scss` and see if that gets things going for you?

**Comment by florianpeninon** [comment]
It solved the problem, thank you!

**Comment by samusgray** [comment]
Awesome. Glad to help!
