### ISSUE TITLE
Unable to install Susy due to fourseven:scss version upgraded to 3.1.1

### ISSUE THREAD

**Issue by nagarajay** [aaronagray/meteor-susy#4]
Hi Aaron,
## Can you please update the package. While installing the package I get this error.

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: fourseven:scss 2.1.1, was 3.1.1.
Constraints on package "fourseven:scss":
- fourseven:scss@2.0.0-beta <- meta:susy 2.1.1
## To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

Thanks
Ajay

**Comment by Eruant** [comment]
Just to let you know fourseven:scss is now running at 3.2.0

**Comment by pigstake** [comment]
@aaronagray :pray: Please update fourseven:scss dependency version to 3.2.0 https://github.com/fourseven/meteor-scss/blob/master/package.js

**Comment by croogie** [comment]
+1

**Comment by samusgray** [comment]
Hey all, I'm sorry this is so late. I didn't notice the notifications until tonight. I merged #5 by @jasondonnette tonight. Please let me know if you have any troubles relating to this request. :D
